import {ColorPropType, StyleSheet} from 'react-native';
 export const styles = StyleSheet.create({
    backgroungStyle:{
        backgroundColor:"#8a2be2",
        width:"100%",
        height:"100%"
    },
    bodyStyle:{
        backgroundColor:"#ffff",
        width:"100%",
        height:"79%",
        marginTop:"43%",
        borderTopLeftRadius:40
    },
    bodyinnerStyle:{
        margin:"5%"
    },
    title:{
        marginTop:40,
        alignSelf:"center",
        fontSize:35,
        fontWeight:"bold",
        color:"#8a2be2"
    },
    textInputStyle:{
        backgroundColor:"#fff",
        marginTop:20
    },
    forgotStyle:{
        fontSize:16,
        fontWeight:"bold",
        color:"#8a2be2",
        marginTop:20,
        marginLeft:200
    },
    buttonStyle:{
        height:56,
        marginTop:40,
        backgroundColor:"#8a2be2"
    },
    bottomtextStyle:{
        marginTop:85,
        fontSize:17,textAlign:"center",
        alignSelf:"center"
    }
})