import {ColorPropType, StyleSheet} from 'react-native';
 export const styles = StyleSheet.create({
    backgroungStyle:{
        backgroundColor:"#8a2be2",
        width:"100%",
        height:"100%"
    },
    bodyStyle:{
        backgroundColor:"#ffff",
        width:"100%",
        height:"85%",
        marginTop:"31%",
        borderTopLeftRadius:40
    },
    bodyinnerStyle:{
        margin:"5%"
    },
    title:{
        marginTop:10,
        alignSelf:"center",
        fontSize:35,
        fontWeight:"bold",
        color:"#8a2be2"
    },
    textInputStyle:{
        backgroundColor:"#fff",
        marginTop:10
    },
    buttonStyle:{
        height:56,
        marginTop:45,
        backgroundColor:"#8a2be2"
    },
    bottomtextStyle:{
        marginTop:85,
        fontSize:17,textAlign:"center",
        alignSelf:"center"
    }
})