import {StyleSheet} from 'react-native';
 export const styles = StyleSheet.create({
    backgroungStyle:{
        backgroundColor:"#ffff",
        width:200,
        height:400
    },
    cardStyle:{
        backgroundColor:"#ffff",
        width:160,
        height:150,
        marginTop:"20%",
        borderRadius:10,marginLeft:10,
        marginRight:10
    },
    bodyinnerStyle:{
        margin:"5%"
    },
    title:{
        marginTop:30,
        alignSelf:"center",
        fontSize:16,
        fontWeight:"bold",
        color:"#8a2be2"
    },
    textAccountStyle:{
        backgroundColor:"#fff",
        marginTop:40,
        fontSize:25,
        alignSelf:"center",
        fontWeight:"bold",
    },
    forgotStyle:{
        fontSize:25,
        fontWeight:"bold",
        color:"#8a2be2",
        marginTop:20,
        marginLeft:200
    },
    buttonStyle:{
        height:56,
        backgroundColor:"#8a2be2"
    },
    bottomtextStyle:{
        marginTop:75,
        fontSize:17,textAlign:"center",
        alignSelf:"center"
    },
    textTailorStyle:{
        marginTop:25,
        fontSize:22,
        fontWeight:"bold",
        color:"#800080",
        marginLeft:10
    },
    bottomTabStyle:{
       
        marginBottom:10,
        borderRadius:2,
        borderWidth:1,
        height:66,
        marginLeft:20,
        marginRight:20,
        marginRight:20
    },
    tabiconStyle:{
        color:"red",fontSize:30,
        marginLeft:40,
        marginTop:7
    },
    tabtextStule:{
       fontSize:16,
       fontWeight:"bold",
       marginBottom:5,
       marginLeft:20
    }
})